services:
  app:
    image: ${APP_IMAGE:-ndr:prod}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-9000}:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ndr}
      POSTGRES_USER: ${POSTGRES_USER:-ndr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ndr}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
