name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PIP_CACHE_DIR: ~/.cache/pip
      DB_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/ndr
      TEST_DB_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/ndr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Prepare database
        run: |
          export PGPASSWORD=postgres
          until psql -h localhost -U postgres -c "SELECT 1"; do
            sleep 2
          done
          psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS ndr;"
          psql -h localhost -U postgres -c "CREATE DATABASE ndr;"
          psql -h localhost -U postgres -d ndr -c "CREATE EXTENSION IF NOT EXISTS ltree;"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
          # tools used only in CI
          pip install pip-audit safety

      - name: Run pre-commit (all files)
        run: pre-commit run --all-files

      - name: Run mypy (baseline)
        run: mypy app || true

      - name: Run tests with coverage (enforce >=85%)
        run: pytest --cov=app --cov-report=term --cov-report=xml --cov-fail-under=85

      - name: Dependency audit (pip-audit)
        run: |
          pip-audit -r requirements.txt -f markdown > pip-audit.md || true
        continue-on-error: true

      - name: Dependency audit (safety)
        run: |
          safety check -r requirements.txt --full-report > safety.txt || true
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-reports
          path: |
            coverage.xml
            pip-audit.md
            safety.txt
